#include "HSWITCH_cfg.h"
#include "../../MCAL/GPIO/GPIO.h"
#include "../../LIB/STD_TYPES.h"

Switch_t Switches[Switch_NUM]=
{
    {GPIO_PORTB,GPIO_PIN3,SWITCH_PULLUP,SWITCH_RELEASED,0,SWITCH_RELEASED,SWITCH_RELEASED},
    {GPIO_PORTB,GPIO_PIN4,SWITCH_PULLUP,SWITCH_RELEASED,0,SWITCH_RELEASED,SWITCH_RELEASED},
    {GPIO_PORTB,GPIO_PIN5,SWITCH_PULLUP,SWITCH_RELEASED,0,SWITCH_RELEASED,SWITCH_RELEASED},
    {GPIO_PORTB,GPIO_PIN6,SWITCH_PULLUP,SWITCH_RELEASED,0,SWITCH_RELEASED,SWITCH_RELEASED},
   

};