

#include "../../LIB/STD_TYPES.h"
#include "../../LIB/STD_MATH.h"
#include "../../MCAL/GPIO/GPIO.h"
#include "LCD_cfg.h"


/*****************************************************************************************************************************************/
/********************************************  Initializtion in case of  8Bit   Mode        **********************************************/
LCD_t LCD_8BIT[LCD_PINS_NUM]=
{
        {GPIO_PORTB, GPIO_PIN8, GPIO_MODE_OUTPUT, GPIO_SPEED_HIGH, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_LOW},
        {GPIO_PORTB, GPIO_PIN9, GPIO_MODE_OUTPUT, GPIO_SPEED_HIGH, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_LOW},
        {GPIO_PORTB, GPIO_PIN10, GPIO_MODE_OUTPUT, GPIO_SPEED_HIGH, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_LOW},
        {GPIO_PORTB, GPIO_PIN0, GPIO_MODE_OUTPUT, GPIO_SPEED_HIGH, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_LOW},
        {GPIO_PORTB, GPIO_PIN1, GPIO_MODE_OUTPUT, GPIO_SPEED_HIGH, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_LOW},
        {GPIO_PORTB, GPIO_PIN2, GPIO_MODE_OUTPUT, GPIO_SPEED_HIGH, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_LOW},
        {GPIO_PORTB, GPIO_PIN3, GPIO_MODE_OUTPUT, GPIO_SPEED_HIGH, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_LOW},
        {GPIO_PORTB, GPIO_PIN4, GPIO_MODE_OUTPUT, GPIO_SPEED_HIGH, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_LOW},
        {GPIO_PORTB, GPIO_PIN5, GPIO_MODE_OUTPUT, GPIO_SPEED_HIGH, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_LOW},
        {GPIO_PORTB, GPIO_PIN6, GPIO_MODE_OUTPUT, GPIO_SPEED_HIGH, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_LOW},
        {GPIO_PORTB, GPIO_PIN7, GPIO_MODE_OUTPUT, GPIO_SPEED_HIGH, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_LOW}
    };

/********************************************  InitiBliztion in cBse of  4Bit   Mode        **********************************************/

    LCD_t LCD_4BIT[LCD_PINS_NUM]=
    {
        {GPIO_PORTA, GPIO_PIN0, GPIO_MODE_OUTPUT, GPIO_SPEED_HIGH, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_LOW},
        {GPIO_PORTA, GPIO_PIN1, GPIO_MODE_OUTPUT, GPIO_SPEED_HIGH, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_LOW},
        {GPIO_PORTA, GPIO_PIN2, GPIO_MODE_OUTPUT, GPIO_SPEED_HIGH, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_LOW},
        {GPIO_PORTB, GPIO_PIN0, GPIO_MODE_OUTPUT, GPIO_SPEED_HIGH, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_LOW},
        {GPIO_PORTB, GPIO_PIN1, GPIO_MODE_OUTPUT, GPIO_SPEED_HIGH, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_LOW},
        {GPIO_PORTB, GPIO_PIN2, GPIO_MODE_OUTPUT, GPIO_SPEED_HIGH, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_LOW},
        {GPIO_PORTB, GPIO_PIN3, GPIO_MODE_OUTPUT, GPIO_SPEED_HIGH, GPIO_OUTPUT_TYPE_PUSH_PULL, GPIO_LOW},
       
    };
/*****************************************************************************************************************************************/
