#include "LEDCfg.h"
#include "../../MCAL/GPIO/GPIO.h"




 LED_t LEDS[LEDs_NUM]=
{
    {GPIO_PORTA,GPIO_PIN0,LED_FORWARD,LED_OFF},
    {GPIO_PORTA,GPIO_PIN1,LED_FORWARD,LED_OFF},
    {GPIO_PORTA,GPIO_PIN2,LED_FORWARD,LED_OFF},


};