#include "HSWITCH_cfg.h"
#include "../../MCAL/GPIO/GPIO.h"
#include "../../LIB/STD_TYPES.h"

Switch_t Switches[Switch_NUM]=
{
    {GPIO_PORTB,GPIO_PIN11,SWITCH_PULLUP,SWITCH_RELEASED,0,SWITCH_RELEASED,SWITCH_RELEASED},
    {GPIO_PORTB,GPIO_PIN12,SWITCH_PULLUP,SWITCH_RELEASED,0,SWITCH_RELEASED,SWITCH_RELEASED},
    {GPIO_PORTB,GPIO_PIN13,SWITCH_PULLDOWN,SWITCH_PRESSED,0,SWITCH_RELEASED,SWITCH_RELEASED},
    {GPIO_PORTB,GPIO_PIN14,SWITCH_PULLDOWN,SWITCH_RELEASED,0,SWITCH_RELEASED,SWITCH_RELEASED},
    {GPIO_PORTA,GPIO_PIN5,SWITCH_PULLUP,SWITCH_RELEASED,0,SWITCH_RELEASED,SWITCH_RELEASED},
    {GPIO_PORTA,GPIO_PIN6,SWITCH_PULLDOWN,SWITCH_PRESSED,0,SWITCH_RELEASED,SWITCH_RELEASED},
    {GPIO_PORTA,GPIO_PIN7,SWITCH_PULLDOWN,SWITCH_RELEASED,0,SWITCH_RELEASED,SWITCH_RELEASED},
    {GPIO_PORTA,GPIO_PIN8,SWITCH_PULLUP,SWITCH_RELEASED,0,SWITCH_RELEASED,SWITCH_RELEASED},

};